### ISSUE TITLE
How do you make a Libretro core in Go?

### ISSUE THREAD

**Issue by tinglar** [libretro/go-playthemall#40]
This project prompted my curiosity; I am surprised that Go can interact with Libretro!

What would I need to do if I want to use Go when writing a Libretro core, especially if I were to write one that _does not_ use OpenGL (in light of the current capabilities this frontend has)?

**Comment by RobLoach** [comment]
Been curious about this myself. Would be neat to get a small example core going.

You'll find some of the examples of function declarations over at https://github.com/libretro/go-playthemall/blob/master/libretro/libretro.go

Need to make `go build` compile a static binary library rather than an executable.

**Comment by tinglar** [comment]
What libraries (besides Libretro) can I use when dealing with graphics and sounds in Go?

**Comment by kivutar** [comment]
It depends how much performance you're willing to trade for ease of programming. I would personally write my own blitter and mixer in pure go to avoid cgo (if possible)

**Comment by kivutar** [comment]
OK the first step then would be to have simple stuff working. For example a core that prints the buttons pressed on the pad to the logs. Like this one https://github.com/libretro/libretro-samples/blob/master/tests/test/libretro-test.c

No display involved.

**Comment by kivutar** [comment]
I close this because it's more a question than an issue or a feature request
